### ISSUE TITLE
Issues when using the Quest 3

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/SubtleGame#43]
When using a Quest 3 + link cable, the headset is recognised by the game as a Quest 3, but both of the controllers are 'stuck' to the left controller. As well as being incorrect, the player cannot progress through the game because both controllers need to be tracking properly to press the buttons (when the interaction modality is set to controllers).

When using a Quest 2 natively, the game recognises the headset as a Quest 2. This means that the controller meshes are Quest 2 ones, but the player is able to progress through the game. However, if the player starts with hands and then switches to controllers later on, it seems like both controllers are registered as left ones, which leaves the player unable to complete that game.

**Comment by Ragzouken** [comment]
We have figured out updating the plugin and getting the correct controller placement, but there's an issue remaining with network connectivity. I thought it was this (https://forum.unity.com/threads/unity-removes-android-permission-internet-in-the-build-apk-after-build-is-completed.1466654/) but that seems to only be an OpenXR thing, which we are not using here.

**Comment by rhoslynroebuck** [comment]
Just tested with a build from main, it doesn't seem to be working either. I can't remember exactly the last I tested with an apk build, but I've definitely done it before with no problems...not sure where this has come from now.

**Comment by Ragzouken** [comment]
Connectivity issue seems to have been unrelated, due to an issue with autoconnect's confusing behavior. @rhoslynroebuck are there any remaining Quest 3 issues?

**Comment by rhoslynroebuck** [comment]
I'm still getting a couple of issues:
- Some of the arrows on the menu buttons are missing 
- The logic for testing whether hands/controllers are being tracked is not working as expected when running the apk on the headset. (Note that I've only tested this for the Quest 2 - my Quest 3 is charging, will test this asap)

**Expected behaviour:**
When the correct input method is being tracked (hands or controllers), the button will appear and be pressable. When the incorrect input method is being tracked, the button will disappear and some text will appear on the canvas to say that the player needs to put down / pick up their controllers. This is currently still working as expected when running through the Unity Editor + Quest link:

https://github.com/IRL2/SubtleGame/assets/50617818/fe51e2ae-d366-4163-bb91-d2bb0296231a


**Incorrect behaviour:**
The button appears and is pressable when the player is using the incorrect input method. This is happening when running the game locally on the headset:

Uploading subtle-game-apk.mp4…

**Comment by rhoslynroebuck** [comment]
The passthrough issue only seems to occur the first time you run the game, it seems to be working fine again now...

**Comment by rhoslynroebuck** [comment]
The enabling/disabling buttons based on interaction mode will be fixed in a separate branch. The issue is that the hands seem to be tracked all of the time, which means that when the hands are the correct interaction mode, the button is always pressable.
